<?php

namespace App;

/**
 * Eloquent class to describe the assuntos table.
 *
 * automatically generated by ModelGenerator.php
 */
class Assuntos extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'assuntos';

    protected $fillable = ['titulo_assunto', 'deleted_at'];

    public function getDates()
    {
        return ['deleted_at'];
    }

    public function assuntos()
    {
        return $this->belongsTo('App\Assuntos', 'raiz_id', 'id');
    }

    public function assuntos()
    {
        return $this->hasMany('App\Assuntos', 'raiz_id', 'id');
    }

    public function programaAssuntos()
    {
        return $this->hasMany('App\ProgramaAssuntos', 'assunto_id', 'id');
    }

    public function questoes()
    {
        return $this->hasMany('App\Questoes', 'assunto_id', 'id');
    }
}
