<?php

namespace App;

/**
 * Eloquent class to describe the bancas table.
 *
 * automatically generated by ModelGenerator.php
 */
class Bancas extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'bancas';

    protected $fillable = ['nome_banca', 'deleted_at'];

    public function getDates()
    {
        return ['deleted_at'];
    }

    public function programaEstudo()
    {
        return $this->hasMany('App\ProgramaEstudo', 'banca_id', 'id');
    }

    public function questoes()
    {
        return $this->hasMany('App\Questoes', 'banca_id', 'id');
    }
}
