<?php

namespace App;

/**
 * Eloquent class to describe the item_questoes table.
 *
 * automatically generated by ModelGenerator.php
 */
class ItemQuestoes extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'item_questoes';

    protected $fillable = ['descricao_item', 'correcao_item', 'deleted_at'];

    public function getDates()
    {
        return ['deleted_at'];
    }

    public function questoes()
    {
        return $this->belongsTo('App\Questoes', 'questao_id', 'id');
    }
}
