<?php

namespace App;

/**
 * Eloquent class to describe the orgaos table.
 *
 * automatically generated by ModelGenerator.php
 */
class Orgaos extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'orgaos';

    protected $fillable = ['name', 'sigla_orgao', 'deleted_at'];

    public function getDates()
    {
        return ['deleted_at'];
    }

    public function programaEstudo()
    {
        return $this->hasMany('App\ProgramaEstudo', 'orgao_id', 'id');
    }

    public function questoes()
    {
        return $this->hasMany('App\Questoes', 'orgao_id', 'id');
    }
}
