<?php

namespace App;

/**
 * Eloquent class to describe the programa_estudo table.
 *
 * automatically generated by ModelGenerator.php
 */
class ProgramaEstudo extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'programa_estudo';

    protected $fillable = ['nome_programa', 'foco_programa', 'meta_diaria', 'deleted_at'];

    public function getDates()
    {
        return ['deleted_at'];
    }

    public function bancas()
    {
        return $this->belongsTo('App\Bancas', 'banca_id', 'id');
    }

    public function orgaos()
    {
        return $this->belongsTo('App\Orgaos', 'orgao_id', 'id');
    }

    public function programaAssuntos()
    {
        return $this->hasMany('App\ProgramaAssuntos', 'programa_id', 'id');
    }
}
