<?php

namespace App;

/**
 * Eloquent class to describe the programa_assuntos table.
 *
 * automatically generated by ModelGenerator.php
 */
class ProgramaAssuntos extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'programa_assuntos';

    public $primaryKey = '';

    public $incrementing = false;

    protected $fillable = ['deleted_at'];

    public function getDates()
    {
        return ['deleted_at'];
    }

    public function assuntos()
    {
        return $this->belongsTo('App\Assuntos', 'assunto_id', 'id');
    }

    public function programaEstudo()
    {
        return $this->belongsTo('App\ProgramaEstudo', 'programa_id', 'id');
    }
}
