<?php

namespace App\Models;

/**
 * Eloquent class to describe the orgaos table.
 *
 * automatically generated by ModelGenerator.php
 */
class Orgaos extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'orgaos';

    protected $fillable = ['name', 'sigla_orgao', 'deleted_at'];

    public static $rules = [
        'sigla_orgao' => 'required|max:255',
    ];

    public function getDates()
    {
        return ['deleted_at'];
    }

    public function questoes()
    {
        return $this->hasMany('App\Models\Questoes', 'orgao_id', 'id');
    }
}
