<?php

namespace App\Models;

/**
 * Eloquent class to describe the programa_estudo table.
 *
 * automatically generated by ModelGenerator.php
 */
class ProgramaEstudo extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'programa_estudo';

    protected $fillable = ['nome_programa', 'foco_programa', 'meta_diaria', 'banca_id', 'orgao_id','deleted_at'];

    public static $rules = [
        'nome_programa' => 'max:100',
    ];
    public function getDates()
    {
        return ['deleted_at'];
    }

    public function bancas()
    {
        return $this->belongsTo('App\Models\Bancas', 'banca_id', 'id');
    }

    public function orgaos()
    {
        return $this->belongsTo('App\Models\Orgaos', 'orgao_id', 'id');
    }

    public function programaAssuntos()
    {
        return $this->hasMany('App\Models\ProgramaAssuntos', 'programa_id', 'id');
    }
}
