<?php

namespace App\Models;

/**
 * Eloquent class to describe the questoes table.
 *
 * automatically generated by ModelGenerator.php
 */
class Questoes extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'questoes';



    public $fillable = [
        'cod_questao',
        'enunciado',
        'modalidade',
        'ano',
        'assunto_id',
        'banca_id',
        'orgao_id'
    ];
     /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'cod_questao' => 'string',
        'enunciado' => 'string',
        'modalidade' => 'integer',
        'ano' => 'date',
        'assunto_id' => 'integer',
        'banca_id' => 'integer',
        'orgao_id' => 'integer'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'cod_questao' => 'required',
        'enunciado' => 'required',
        'modalidade' => 'required',
        'ano' => 'required',
        'assunto_id' => 'required',
        'banca_id' => 'required',
        'orgao_id' => 'required'
    ];

    public function getDates()
    {
        return ['ano', 'deleted_at'];
    }

    public function assuntos()
    {
        return $this->belongsTo('App\Models\Assuntos', 'assunto_id', 'id');
    }

    public function bancas()
    {
        return $this->belongsTo('App\Models\Bancas', 'banca_id', 'id');
    }

    public function orgaos()
    {
        return $this->belongsTo('App\Models\Orgaos', 'orgao_id', 'id');
    }

    public function itemQuestoes()
    {
        return $this->hasMany('App\Models\ItemQuestoes', 'questao_id', 'id');
    }
}
